/*
 * Copyright Strimzi authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */
package io.strimzi.testclients.testutils;

import io.strimzi.test.container.StrimziKafkaCluster;
import org.apache.kafka.clients.CommonClientConfigs;
import org.apache.kafka.common.config.SslConfigs;
import org.apache.kafka.common.security.auth.SecurityProtocol;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import java.security.cert.Certificate;
import java.util.Base64;
import java.util.Collections;
import java.util.Map;

/**
 * Converts the PKCS12 client stores generated by {@link StrimziKafkaCluster} into the PEM strings
 * the test clients expect in CA_CRT, USER_CRT and USER_KEY (and the admin client behind `configure ssl`).
 */
public class TlsUtils {

    private static final Base64.Encoder PEM_ENCODER = Base64.getMimeEncoder(64, "\n".getBytes(StandardCharsets.US_ASCII));

    /**
     * Configuration of a plain Kafka client connecting to the TLS cluster, used to verify what the test clients did.
     */
    public static Map<String, Object> kafkaClientConfig(StrimziKafkaCluster cluster) throws Exception {
        return Map.of(
            CommonClientConfigs.BOOTSTRAP_SERVERS_CONFIG, cluster.getBootstrapServers(),
            CommonClientConfigs.SECURITY_PROTOCOL_CONFIG, SecurityProtocol.SSL.name,
            SslConfigs.SSL_TRUSTSTORE_TYPE_CONFIG, "PEM",
            SslConfigs.SSL_TRUSTSTORE_CERTIFICATES_CONFIG, caCertificate(cluster),
            SslConfigs.SSL_KEYSTORE_TYPE_CONFIG, "PEM",
            SslConfigs.SSL_KEYSTORE_CERTIFICATE_CHAIN_CONFIG, userCertificateChain(cluster),
            SslConfigs.SSL_KEYSTORE_KEY_CONFIG, userKey(cluster)
        );
    }

    public static String caCertificate(StrimziKafkaCluster cluster) throws Exception {
        KeyStore trustStore = load(cluster.getClientTrustStoreBytes(), cluster.getClientStorePassword());
        StringBuilder pem = new StringBuilder();

        for (String alias : Collections.list(trustStore.aliases())) {
            if (trustStore.isCertificateEntry(alias)) {
                pem.append(toPem("CERTIFICATE", trustStore.getCertificate(alias).getEncoded()));
            }
        }

        return pem.toString();
    }

    public static String userCertificateChain(StrimziKafkaCluster cluster) throws Exception {
        KeyStore keyStore = load(cluster.getClientKeyStoreBytes(), cluster.getClientStorePassword());
        StringBuilder pem = new StringBuilder();

        for (Certificate certificate : keyStore.getCertificateChain(keyAlias(keyStore))) {
            pem.append(toPem("CERTIFICATE", certificate.getEncoded()));
        }

        return pem.toString();
    }

    public static String userKey(StrimziKafkaCluster cluster) throws Exception {
        KeyStore keyStore = load(cluster.getClientKeyStoreBytes(), cluster.getClientStorePassword());
        char[] password = cluster.getClientStorePassword().toCharArray();

        // getEncoded() of a private key is PKCS#8, the unencrypted PEM form Kafka accepts without ssl.key.password
        return toPem("PRIVATE KEY", keyStore.getKey(keyAlias(keyStore), password).getEncoded());
    }

    private static KeyStore load(byte[] storeBytes, String password) throws Exception {
        KeyStore store = KeyStore.getInstance("PKCS12");
        store.load(new ByteArrayInputStream(storeBytes), password.toCharArray());
        return store;
    }

    private static String keyAlias(KeyStore keyStore) throws Exception {
        for (String alias : Collections.list(keyStore.aliases())) {
            if (keyStore.isKeyEntry(alias)) {
                return alias;
            }
        }

        throw new IllegalStateException("Client keystore contains no private key entry");
    }

    private static String toPem(String type, byte[] der) {
        return "-----BEGIN " + type + "-----\n" + PEM_ENCODER.encodeToString(der) + "\n-----END " + type + "-----\n";
    }
}
